### ISSUE TITLE
Docker image to skip the installation process

### ISSUE THREAD

**Issue by dibyadas** [Parth-Vader/MobOff#50]
The docker image will have the MobOff and it's dependencies installed. Will make it even easier to use.

**Comment by Parth-Vader** [comment]
@dibyadas Yes, good point.

**Comment by Parth-Vader** [comment]
@ashwani99 Sure, can you just let me know what are the steps you want to take? :smile:

**Comment by ashwani99** [comment]
@Parth-Vader We can simplify the installation process by 2 ways.
1. To make it available on PyPi so that users can install it via `pip`. I guess we already have it on PyPi https://pypi.org/project/MobOff/ I can initiate a `requirements.txt` file and refactor the `setup.py` file to get the dependencies. If we can tell the users install it via `pip`, it will be easier for them.
2. Another way is to create a dockerfile and let the users run it with docker. The dockerfile will take care of installing right version of Python, installing dependencies. 

I think the first option is more suitable for the needs of the project but we may also include a dockerfile for users who want to run it with Docker. What do you think?

**Comment by rajula96reddy** [comment]
@ashwani99 Hey! Both the options sound good. Can we try to do both? We can create a new issue for having the `requirements.txt` file. Also for the second option, we can start with `Dockerfile` and also publish a docker image. I can help with creating and publishing a docker image.

**Comment by ashwani99** [comment]
@rajula96reddy https://github.com/Parth-Vader/MobOff/issues/51

**Comment by Parth-Vader** [comment]
I like the idea of building a Docker Image for MobOff. @ashwani99 Would you like to do it?

**Comment by ashwani99** [comment]
Sure @Parth-Vader But I am new to building Docker images. I will get a hang of it and comment what all steps I would take to add a Docker Image for MobOff. Can I get assigned the issue?

**Comment by rajula96reddy** [comment]
@ashwani99 Let me know if you face any problems with building Docker images
